package net.tclproject.immersivecavegen;

import net.minecraftforge.common.config.*;
import cpw.mods.fml.common.event.*;
import cpw.mods.fml.common.*;
import java.io.*;
import cpw.mods.fml.client.event.*;
import cpw.mods.fml.common.eventhandler.*;

public class WGConfig
{
    public static Configuration config;
    public static boolean oneBigCave;
    public static boolean oldGen;
    public static boolean enableBetterSand;
    public static boolean enableBetterCaverns;
    public static boolean enableBetterMineshafts;
    public static boolean enablePopChanges;
    public static boolean turnOffVanillaCaverns;
    public static boolean turnOffVanillaUndergroundDirt;
    public static boolean caveDecorations;
    public static boolean realisticCobwebs;
    public static int widthAdditionNormal;
    public static int widthAdditionColossal;
    public static int widthAdditionRegional;
    public static int widthAdditionCircular;
    public static int widthAdditionRavineCave;
    public static int widthAdditionVertical;
    public static int widthAdditionMaze;
    public static int widthAdditionBranchPoint;
    public static int widthAdditionDirectional;
    public static int additionalCavesInClusterLength;
    public static int additionalCavesInClusterAmount;
    public static boolean hardLimitsEnabled;
    public static int widthMaxNormal;
    public static int widthMaxColossal;
    public static int widthMaxRegional;
    public static int widthMaxCircular;
    public static int widthMaxRavineCave;
    public static int widthMaxVertical;
    public static int widthMaxMaze;
    public static int widthMaxBranchPoint;
    public static int widthMaxDirectional;
    public static int maxCavesInClusterLength;
    public static int maxCavesInClusterAmount;
    public static int widthMinNormal;
    public static int widthMinColossal;
    public static int widthMinRegional;
    public static int widthMinCircular;
    public static int widthMinRavineCave;
    public static int widthMinVertical;
    public static int widthMinMaze;
    public static int widthMinBranchPoint;
    public static int widthMinDirectional;
    public static int minCavesInClusterLength;
    public static int minCavesInClusterAmount;
    public static int waterLakesChance;
    public static int lavaLakesChance;
    public static int caveNormalReductionPercentage;
    public static int caveColossalReductionPercentage;
    public static int caveRegionalReductionPercentage;
    public static int caveCircularRoomReductionPercentage;
    public static int caveRavineCaveReductionPercentage;
    public static int caveVerticalReductionPercentage;
    public static int caveMazeReductionPercentage;
    public static int undergWaterLakesChance;
    public static int undergLavaLakesChance;
    public static boolean waterCaves;
    public static boolean netherCaves;
    public static boolean jumpscare;
    public static boolean serveronly;
    public static float liliesChance;
    public static float treeChance;
    public static int glowLilies;
    public static boolean fcaves;
    public static boolean icaves;
    public static boolean jcaves;
    public static boolean scaves;
    public static boolean wcaves;
    public static boolean lcaves;
    public static boolean disableSourceWater;
    public static boolean disableSourceLava;
    public static boolean disableSourceUnderground;
    public static float generationDensity;
    public static boolean livingCavesLush;
    public static boolean enableMineshaftSpawn;
    public static boolean enableDungeonSpawn;
    public static boolean enableStrongholdSpawn;
    public static boolean enableVillageSpawn;
    public static boolean enableCaveSpiderSpawnerSpawn;
    public static boolean enableCaveSpiderSpawnerSpawnAlways;
    public static boolean enableDesolateSpawn;
    public static boolean secondYLevel;
    public static boolean enableEntities;
    public static boolean glowSlimesSpawnWater;
    public static int floodLevel;
    public static int floodMech;
    public static String[] fcaveslist;
    public static String[] icaveslist;
    public static String[] jcaveslist;
    public static String[] pcaveslist;
    public static String[] scaveslist;
    public static String[] wcaveslist;
    public static String[] lcaveslist;
    public static String[] dimblacklist;
    public static String[] secondYLevelList;
    public static int cavernsSpawnMultiplier;
    public static int cavesSpawnMultiplier;
    public static int oldBigCavesSpawnMultiplier;
    public static int giantCaveChance;
    public static int entitySmBrSpID;
    public static int entityBrSpID;
    public static int entityLBrSpID;
    public static int entityGlSlID;
    public static int mobSpawnChance;
    public static String CATEGORY_LIMITS;
    public static String CATEGORY_WORLD;
    public static String CATEGORY_TYPES;
    public static String CATEGORY_DECO;
    public static String CATEGORY_MOBS;
    public static String CATEGORY_REDUX;
    public static String CATEGORY_MODIF;

    public static void init(final String configDir, final FMLPreInitializationEvent event) {
        FMLCommonHandler.instance().bus().register((Object)new WGConfig());
        if (WGConfig.config == null) {
            final File path = new File(configDir + "/immersivecavegen.cfg");
            WGConfig.config = new Configuration(path);
            loadConfiguration();
        }
    }

    public static void loadConfiguration() {
        WGConfig.config.load();
        WGConfig.enableEntities = WGConfig.config.getBoolean("Enable Mobs", WGConfig.CATEGORY_MOBS, true, "An option to disable the mod's mobs as a whole.");
        WGConfig.glowSlimesSpawnWater = WGConfig.config.getBoolean("Glowslimes Spawn Water", WGConfig.CATEGORY_MOBS, true, "An option to disable the special ability of glowslimes to spawn water.");
        WGConfig.mobSpawnChance = WGConfig.config.getInt("Mob Spawn Chance", WGConfig.CATEGORY_MOBS, 30, 1, 1000, "How often custom mobs spawn, 1 being the caves are absolutely flooded with them, 10 being the default and 1000 being almost never.");
        WGConfig.entitySmBrSpID = WGConfig.config.getInt("Small Brown Spider ID", WGConfig.CATEGORY_MOBS, -1, -1, 1000000, "-1 is random free ID. Set to something else if you want a fixed entity ID.");
        WGConfig.entityBrSpID = WGConfig.config.getInt("Brown Spider ID", WGConfig.CATEGORY_MOBS, -1, -1, 1000000, "-1 is random free ID. Set to something else if you want a fixed entity ID.");
        WGConfig.entityLBrSpID = WGConfig.config.getInt("Large Brown Spider ID", WGConfig.CATEGORY_MOBS, -1, -1, 1000000, "-1 is random free ID. Set to something else if you want a fixed entity ID.");
        WGConfig.entityGlSlID = WGConfig.config.getInt("Glowslime ID", WGConfig.CATEGORY_MOBS, -1, -1, 1000000, "-1 is random free ID. Set to something else if you want a fixed entity ID.");
        WGConfig.oneBigCave = WGConfig.config.getBoolean("Exteme Cave Gen", WGConfig.CATEGORY_WORLD, false, "Makes the world underground a HUGE cavern system. A bit extreme, not many will like it, but the option is there. (Note: Does not work with Old Cave Gen option)");
        WGConfig.enableBetterCaverns = WGConfig.config.getBoolean("Enable Caverns Replacer", WGConfig.CATEGORY_WORLD, true, "Replaces the vanilla caverns with custom.");
        WGConfig.enableBetterSand = WGConfig.config.getBoolean("Enable Better Sand Generation", WGConfig.CATEGORY_WORLD, true, "Improved sand generation.");
        WGConfig.enableBetterMineshafts = WGConfig.config.getBoolean("Enable Better Mineshafts", WGConfig.CATEGORY_WORLD, true, "Makes mineshafts spawn less chaotically and in better mineshaft systems.");
        WGConfig.enablePopChanges = WGConfig.config.getBoolean("Enable World Population Changes", WGConfig.CATEGORY_WORLD, true, "Disables liquid source block and lake spawn changes and toggles for stucture spawns, for better mod compatibility. If something conflicts with another mod, the first thing you should try disabling is this. The second is 'Separate Flooded Y Level'.");
        WGConfig.turnOffVanillaCaverns = WGConfig.config.getBoolean("Disable Vanilla Caverns", WGConfig.CATEGORY_WORLD, false, "Disables vanilla, non-custom cavern spawning completely.");
        WGConfig.turnOffVanillaUndergroundDirt = WGConfig.config.getBoolean("Disable Vanilla Underground Dirt", WGConfig.CATEGORY_WORLD, false, "Prevents vanilla from spawning patches of dirt underground. Please note this will likely have no effect on vanilla gen replacers, such as CoFH Core.");
        WGConfig.oldGen = WGConfig.config.getBoolean("Old Cave Gen", WGConfig.CATEGORY_WORLD, false, "Instead of using TMCU4 cave gen, uses TMCU2 cave gen.");
        WGConfig.cavernsSpawnMultiplier = WGConfig.config.getInt("Caverns Spawn Frequency Multiplier", WGConfig.CATEGORY_WORLD, 1, 0, 50, "Value from 0 to 50. The default is 1, which is how they generate normally.");
        WGConfig.cavesSpawnMultiplier = WGConfig.config.getInt("Caves Spawn Frequency Multiplier", WGConfig.CATEGORY_WORLD, 1, 0, 50, "Value from 0 to 50, 0 totally turning off caves and 50 being a world totally filled with them. The default is 1, which is how they generate in vanilla minecraft.");
        WGConfig.oldBigCavesSpawnMultiplier = WGConfig.config.getInt("Old Big Caves Spawn Frequency Multiplier", WGConfig.CATEGORY_WORLD, 1, 0, 50, "Big caves frequency multiplier that only works with 'Old Cave Gen' as true.");
        WGConfig.giantCaveChance = WGConfig.config.getInt("Extra Mega Cave Chance", WGConfig.CATEGORY_WORLD, 0, 0, 100, "Note: This will only affect caves that *can* be big. There are going to be some small caves even if you turn this to 100. Note 2: This is NOT percentages. 100 does not mean caves have 100% chance to be big, it simply means they're 100 'x' more likely to be big.");
        WGConfig.waterCaves = WGConfig.config.getBoolean("Water Flooded Caves", WGConfig.CATEGORY_WORLD, true, "Some water-flooded caves will spawn. if you think it's not immersive but annoying, you can turn it off :p");
        WGConfig.netherCaves = WGConfig.config.getBoolean("Enable Nether Decoration", WGConfig.CATEGORY_WORLD, false, "Applies the nether stalactites, plants etc. in worldgen to the nether as well. A bit wacky, so off by default.");
        WGConfig.jumpscare = WGConfig.config.getBoolean("Effects", WGConfig.CATEGORY_WORLD, true, "Surprise! (Only keep reading if you hate surprises)(Randomly (but rarely) applies blindness below y=35 and plays a sound).");
        WGConfig.widthAdditionNormal = WGConfig.config.getInt("Normal Cave Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionColossal = WGConfig.config.getInt("Colossal Cave Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionRegional = WGConfig.config.getInt("Regional Cave Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionCircular = WGConfig.config.getInt("Circular Cave Room Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionRavineCave = WGConfig.config.getInt("Ravine Cave Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionVertical = WGConfig.config.getInt("Vertical Cave Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionMaze = WGConfig.config.getInt("Maze Cave Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionBranchPoint = WGConfig.config.getInt("Cave Branch Point Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.widthAdditionDirectional = WGConfig.config.getInt("Directional Cave Width Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 12, "Value from -5 to 12, manually modifies the width of a specific type of caves. Doesn't work with Old Cave Gen option.");
        WGConfig.additionalCavesInClusterLength = WGConfig.config.getInt("Cave Length in Cluster Modifier", WGConfig.CATEGORY_MODIF, 0, -50, 100, "Value from -3 to 50, manually modifies the cave length in a cave cluster. Doesn't work with Old Cave Gen option.");
        WGConfig.additionalCavesInClusterAmount = WGConfig.config.getInt("Caves in Cluster Modifier", WGConfig.CATEGORY_MODIF, 0, -12, 50, "Value from -3 to 12, manually modifies the amount of caves in a cave cluster. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxNormal = WGConfig.config.getInt("Normal Cave Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxColossal = WGConfig.config.getInt("Colossal Cave Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxRegional = WGConfig.config.getInt("Regional Cave Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxCircular = WGConfig.config.getInt("Circular Cave Room Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxRavineCave = WGConfig.config.getInt("Ravine Cave Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxVertical = WGConfig.config.getInt("Vertical Cave Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxMaze = WGConfig.config.getInt("Maze Cave Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxBranchPoint = WGConfig.config.getInt("Cave Branch Point Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMaxDirectional = WGConfig.config.getInt("Directional Cave Max Width", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.maxCavesInClusterLength = WGConfig.config.getInt("Max Cave Length in Cluster", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max cave length in a cave cluster. Doesn't work with Old Cave Gen option.");
        WGConfig.maxCavesInClusterAmount = WGConfig.config.getInt("Max Caves in Cluster", WGConfig.CATEGORY_LIMITS, 1000, 0, 1000, "Allows to set max amount of caves in a cave cluster. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinNormal = WGConfig.config.getInt("Normal Cave Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinColossal = WGConfig.config.getInt("Colossal Cave Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinRegional = WGConfig.config.getInt("Regional Cave Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinCircular = WGConfig.config.getInt("Circular Cave Room Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinRavineCave = WGConfig.config.getInt("Ravine Cave Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinVertical = WGConfig.config.getInt("Vertical Cave Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinMaze = WGConfig.config.getInt("Maze Cave Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinBranchPoint = WGConfig.config.getInt("Cave Branch Point Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.widthMinDirectional = WGConfig.config.getInt("Directional Cave Min Width", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min width of a specific type of cave. Doesn't work with Old Cave Gen option.");
        WGConfig.minCavesInClusterLength = WGConfig.config.getInt("Min Cave Length in Cluster", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min cave length in a cave cluster. Doesn't work with Old Cave Gen option.");
        WGConfig.minCavesInClusterAmount = WGConfig.config.getInt("Min Caves in Cluster", WGConfig.CATEGORY_LIMITS, 0, 0, 1000, "Allows to set min amount of caves in a cave cluster. Doesn't work with Old Cave Gen option.");
        WGConfig.hardLimitsEnabled = WGConfig.config.getBoolean("Enable Hard Limits", WGConfig.CATEGORY_LIMITS, false, "Turning this on is required for the min-max settings to take effect. Treat this as a 'I know what I'm doing!' switch.");
        WGConfig.caveDecorations = WGConfig.config.getBoolean("Spawn Cave Decorations", WGConfig.CATEGORY_WORLD, true, "Stalactites, stalagmites, vines etc. will not spawn if you turn this off.");
        WGConfig.realisticCobwebs = WGConfig.config.getBoolean("Realistic Cobwebs", WGConfig.CATEGORY_WORLD, true, "Makes it possible to burn cobwebs with torches/flint and steel. Backport of the 1.14+ Realistic Cobwebs mod. Will disable itself if 'serveronly' is enabled.");
        WGConfig.serveronly = WGConfig.config.getBoolean("Server Only", WGConfig.CATEGORY_WORLD, false, "Custom items, blocks etc. will not be registered effectively allowing the mod to be server-only. Will disable Realistic Cobwebs config option. Note: Because of https://github.com/MinecraftForge/FML/issues/510 vanilla clients can't join. Nothing I can do, if you know a way around this please notify me.");
        WGConfig.disableSourceLava = WGConfig.config.getBoolean("Disable Lava Source Block Gen", WGConfig.CATEGORY_WORLD, false, "Don't know about you, but I hate it when a random source block sets a forest on fire.");
        WGConfig.disableSourceWater = WGConfig.config.getBoolean("Disable Water Source Block Gen", WGConfig.CATEGORY_WORLD, false, "Don't know about you, but I find random water falling down on lava lakes in fire caves pretty annoying and immersion-ruining. Note: Does NOT affect 'Water Flooded Caves', you can turn that off separately.");
        WGConfig.disableSourceUnderground = WGConfig.config.getBoolean("Only Disable Source Gen Underground", WGConfig.CATEGORY_WORLD, false, "If set to true, changes in 'disable lava source block gen' and 'disable water source block gen' will only apply if underground.");
        WGConfig.secondYLevel = WGConfig.config.getBoolean("Separate Flooded Y Level", WGConfig.CATEGORY_WORLD, true, "As an attempt to create something similar to subterranean waters, some caves in and around 'deep ocean's have a separate fixed average Y level below which they're flooded with water.");
        WGConfig.livingCavesLush = WGConfig.config.getBoolean("Lush Living Caves", WGConfig.CATEGORY_TYPES, false, "Living caves that spawn under swamps not only have some occasional trees and flowers but also dirt, grass etc.");
        WGConfig.enableMineshaftSpawn = WGConfig.config.getBoolean("Enable Mineshafts Spawn", WGConfig.CATEGORY_WORLD, true, "Gives option to disable mineshafts from spawning.");
        WGConfig.enableStrongholdSpawn = WGConfig.config.getBoolean("Enable Stronghold Spawn", WGConfig.CATEGORY_WORLD, true, "Gives option to disable strongholds from spawning.");
        WGConfig.enableDungeonSpawn = WGConfig.config.getBoolean("Enable Dungeon Spawn", WGConfig.CATEGORY_WORLD, true, "Gives option to disable dungeons from spawning.");
        WGConfig.enableVillageSpawn = WGConfig.config.getBoolean("Enable Village Spawn", WGConfig.CATEGORY_WORLD, true, "Gives option to disable villages from spawning.");
        WGConfig.enableCaveSpiderSpawnerSpawn = WGConfig.config.getBoolean("Enable Cave Spider Spawner Spawn", WGConfig.CATEGORY_WORLD, true, "Gives option to disable cave spider spawners in mineshafts from spawning.");
        WGConfig.enableCaveSpiderSpawnerSpawnAlways = WGConfig.config.getBoolean("Cave Spider Spawner Spawns Always", WGConfig.CATEGORY_WORLD, false, "Makes EVERY mineshaft corridor spawn with a cave spider spawner and cobwebs. The hardcore version of mineshafts.");
        WGConfig.enableDesolateSpawn = WGConfig.config.getBoolean("Plain World", WGConfig.CATEGORY_WORLD, false, "Gives option to disable scattered features from spawning.");
        WGConfig.floodLevel = WGConfig.config.getInt("Filled Caves Y Level", WGConfig.CATEGORY_WORLD, 4, 1, 256, "Air blocks under this point will always be replaced with water/lava (depends on the other config settings). NOTE: As many things, doesn't support old cave gen option.");
        WGConfig.floodMech = WGConfig.config.getInt("Filled Caves Spawn Mechanism", WGConfig.CATEGORY_WORLD, 1, 1, 2, "1 - Lava, 2 - Water. NOTE: As many things, doesn't support old cave gen option.");
        WGConfig.waterLakesChance = WGConfig.config.getInt("Water Lakes Chance", WGConfig.CATEGORY_WORLD, 12, 1, 100000, "Allows to control water lake frequencies. The less the number, the more frequently they spawn, so 1 = they spawn more oftenly, 10000 = close to never.");
        WGConfig.lavaLakesChance = WGConfig.config.getInt("Lava Lakes Chance", WGConfig.CATEGORY_WORLD, 30, 1, 100000, "Allows to control lava lake frequencies. The less the number, the more frequently they spawn, so 1 = they spawn more oftenly, 10000 = close to never.");
        WGConfig.caveNormalReductionPercentage = WGConfig.config.getInt("Normal Cave Reduction Percentage", WGConfig.CATEGORY_REDUX, 0, 0, 100, "Allows to make normal caves even less common.");
        WGConfig.caveColossalReductionPercentage = WGConfig.config.getInt("Colossal Cave Reduction Percentage", WGConfig.CATEGORY_REDUX, 0, 0, 100, "Allows to make colossal caves even less common.");
        WGConfig.caveRegionalReductionPercentage = WGConfig.config.getInt("Regional Cave Reduction Percentage", WGConfig.CATEGORY_REDUX, 0, 0, 100, "Allows to make regional caves even less common.");
        WGConfig.caveCircularRoomReductionPercentage = WGConfig.config.getInt("Circular Cave Room Reduction Percentage", WGConfig.CATEGORY_REDUX, 0, 0, 100, "Allows to make circular cave rooms even less common.");
        WGConfig.caveRavineCaveReductionPercentage = WGConfig.config.getInt("Ravine Cave Reduction Percentage", WGConfig.CATEGORY_REDUX, 0, 0, 100, "Allows to make normal ravine caves even less common. Note: Ravine caves are different from ravines/caverns! They're not the same thing!");
        WGConfig.caveVerticalReductionPercentage = WGConfig.config.getInt("Vertical Cave Reduction Percentage", WGConfig.CATEGORY_REDUX, 0, 0, 100, "Allows to make normal vertical even less common.");
        WGConfig.caveMazeReductionPercentage = WGConfig.config.getInt("Maze Cave Reduction Percentage", WGConfig.CATEGORY_REDUX, 0, 0, 100, "Allows to make maze caves even less common.");
        WGConfig.undergWaterLakesChance = WGConfig.config.getInt("Underground Water Lakes Chance", WGConfig.CATEGORY_WORLD, 24, 1, 100000, "Allows to control underground water lake frequencies. The less the number, the more frequently they spawn, so 1 = they spawn more oftenly, 10000 = close to never.");
        WGConfig.undergLavaLakesChance = WGConfig.config.getInt("Underground Lava Lakes Chance", WGConfig.CATEGORY_WORLD, 24, 1, 100000, "Allows to control underground lava lake frequencies. The less the number, the more frequently they spawn, so 1 = they spawn more oftenly, 10000 = close to never.");
        WGConfig.generationDensity = WGConfig.config.getFloat("Decoration Density Modifier", WGConfig.CATEGORY_WORLD, 0.8f, 0.0f, 1.0f, "The bigger the number, the more likely a stalactite/staalagmite/glowshroom/other decoration will spawn for every block of a cave.");
        WGConfig.treeChance = WGConfig.config.getFloat("Tree Type Spawn Change", WGConfig.CATEGORY_WORLD, 0.5f, 0.0f, 1.0f, "If living caves are enabled, trees can spawn in them. The closer this number to 0, the more likely a tree will be dead, the closer to 1, the more likely it will be alive.");
        WGConfig.liliesChance = WGConfig.config.getFloat("Underground Lilies Spawn Change", WGConfig.CATEGORY_WORLD, 0.5f, 0.0f, 1.0f, "How often a lily will try to spawn underground. 1F does *not* mean every underground water block will have lily.");
        WGConfig.glowLilies = WGConfig.config.getInt("Underground Lilies Spawn Mode", WGConfig.CATEGORY_WORLD, 1, 1, 3, "1 - Glow in mushroom caves, normal everywhere else. 2 - Glow everywhere. 3 - Normal everywhere. (To turn off completely, use 'Chance' setting).");
        WGConfig.fcaves = WGConfig.config.getBoolean("Generate Fire Caves", WGConfig.CATEGORY_TYPES, true, "If false, other applicable cave types will generate instead.");
        WGConfig.icaves = WGConfig.config.getBoolean("Generate Ice Caves", WGConfig.CATEGORY_TYPES, true, "If false, other applicable cave types will generate instead.");
        WGConfig.jcaves = WGConfig.config.getBoolean("Generate Mushroom Caves", WGConfig.CATEGORY_TYPES, true, "If false, other applicable cave types will generate instead.");
        WGConfig.scaves = WGConfig.config.getBoolean("Generate Sand Caves", WGConfig.CATEGORY_TYPES, true, "If false, other applicable cave types will generate instead.");
        WGConfig.wcaves = WGConfig.config.getBoolean("Generate Water Caves", WGConfig.CATEGORY_TYPES, true, "If false, other applicable cave types will generate instead.");
        WGConfig.lcaves = WGConfig.config.getBoolean("Generate Living Caves", WGConfig.CATEGORY_TYPES, true, "If false, other applicable cave types will generate instead.");
        WGConfig.fcaveslist = WGConfig.config.getStringList("Fire Caves Decoration", WGConfig.CATEGORY_DECO, new String[] { "0.5F", "0.5F", "0.5F", "1.0E-2F", "0.0F", "0.0F" }, "The chances of x decoration spawning, as follows: [Lava stalactites, fiery cave plants, scorched lava stone, skulls, nothing, nothing]");
        WGConfig.icaveslist = WGConfig.config.getStringList("Ice Caves Decoration", WGConfig.CATEGORY_DECO, new String[] { "0.3F", "0.2F", "0.6F", "1.0E-2F", "0.5F", "0.0F" }, "The chances of x decoration spawning, as follows: [Iceshrooms, web, icicles, skulls, stalactites, stalactites]");
        WGConfig.jcaveslist = WGConfig.config.getStringList("Mushroom Caves Decoration", WGConfig.CATEGORY_DECO, new String[] { "0.5F", "0.6F", "0.15F", "0.4F", "0.5F", "0.3F" }, "The chances of x decoration spawning, as follows: [Glowshrooms, vines, web, huge glowshrooms, mushrooms, stalactites]");
        WGConfig.pcaveslist = WGConfig.config.getStringList("Plain Caves Decoration", WGConfig.CATEGORY_DECO, new String[] { "0.15F", "0.2F", "0.5F", "0.1F", "1.0E-2F", "0.0F" }, "The chances of x decoration spawning, as follows: [Vines, web, stalactites, glowshrooms, skulls, nothing]");
        WGConfig.scaveslist = WGConfig.config.getStringList("Sand Caves Decoration", WGConfig.CATEGORY_DECO, new String[] { "0.5F", "0.2F", "0.5F", "1.0E-2F", "0.5F", "0.0F" }, "The chances of x decoration spawning, as follows: [Sand stalactites, web, nothing, skulls, stalactites, nothing]");
        WGConfig.wcaveslist = WGConfig.config.getStringList("Water Caves Decoration", WGConfig.CATEGORY_DECO, new String[] { "0.3F", "0.4F", "0.15F", "0.2F", "1.0E-2F", "0.5F" }, "The chances of x decoration spawning, as follows: [Glowshrooms, water, vines, web, skulls, stalactites]");
        WGConfig.lcaveslist = WGConfig.config.getStringList("Living Caves Decoration", WGConfig.CATEGORY_DECO, new String[] { "0.7F", "0.6F", "0.15F", "0.4F", "0.4F", "0.3F" }, "The chances of x decoration spawning, as follows: [Flowers and dead shrubs, vines, web, trees, mushrooms, stalactites]");
        WGConfig.dimblacklist = WGConfig.config.getStringList("Dimension Blacklist", WGConfig.CATEGORY_REDUX, new String[] { "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" }, "Dimensions the changes will mostly not affect.");
        WGConfig.secondYLevelList = WGConfig.config.getStringList("Biomes Second Y Level Affects", WGConfig.CATEGORY_WORLD, new String[] { "Deep Ocean", "Deep Ocean", "Deep Ocean", "Deep Ocean", "Deep Ocean", "Deep Ocean", "Deep Ocean" }, "Biomes that the 'second Y level' will apply to. Replace one or more of the 'Deep Ocean's with another biome to use.");
        if (WGConfig.config.hasChanged()) {
            WGConfig.config.save();
        }
    }

    @SubscribeEvent
    public void onConfigChange(final ConfigChangedEvent event) {
        if (event.modID.equalsIgnoreCase("immersivecavegen")) {
            loadConfiguration();
        }
    }

    public static Configuration getConfiguration() {
        return WGConfig.config;
    }

    static {
        WGConfig.oneBigCave = false;
        WGConfig.oldGen = false;
        WGConfig.enableBetterSand = true;
        WGConfig.enableBetterCaverns = true;
        WGConfig.enableBetterMineshafts = true;
        WGConfig.enablePopChanges = true;
        WGConfig.turnOffVanillaCaverns = false;
        WGConfig.turnOffVanillaUndergroundDirt = false;
        WGConfig.caveDecorations = true;
        WGConfig.realisticCobwebs = true;
        WGConfig.widthAdditionNormal = 0;
        WGConfig.widthAdditionColossal = 0;
        WGConfig.widthAdditionRegional = 0;
        WGConfig.widthAdditionCircular = 0;
        WGConfig.widthAdditionRavineCave = 0;
        WGConfig.widthAdditionVertical = 0;
        WGConfig.widthAdditionMaze = 0;
        WGConfig.widthAdditionBranchPoint = 0;
        WGConfig.widthAdditionDirectional = 0;
        WGConfig.additionalCavesInClusterLength = 0;
        WGConfig.additionalCavesInClusterAmount = 0;
        WGConfig.hardLimitsEnabled = false;
        WGConfig.widthMaxNormal = 0;
        WGConfig.widthMaxColossal = 0;
        WGConfig.widthMaxRegional = 0;
        WGConfig.widthMaxCircular = 0;
        WGConfig.widthMaxRavineCave = 0;
        WGConfig.widthMaxVertical = 0;
        WGConfig.widthMaxMaze = 0;
        WGConfig.widthMaxBranchPoint = 0;
        WGConfig.widthMaxDirectional = 0;
        WGConfig.maxCavesInClusterLength = 0;
        WGConfig.maxCavesInClusterAmount = 0;
        WGConfig.widthMinNormal = 0;
        WGConfig.widthMinColossal = 0;
        WGConfig.widthMinRegional = 0;
        WGConfig.widthMinCircular = 0;
        WGConfig.widthMinRavineCave = 0;
        WGConfig.widthMinVertical = 0;
        WGConfig.widthMinMaze = 0;
        WGConfig.widthMinBranchPoint = 0;
        WGConfig.widthMinDirectional = 0;
        WGConfig.minCavesInClusterLength = 0;
        WGConfig.minCavesInClusterAmount = 0;
        WGConfig.waterLakesChance = 12;
        WGConfig.lavaLakesChance = 30;
        WGConfig.caveNormalReductionPercentage = 0;
        WGConfig.caveColossalReductionPercentage = 0;
        WGConfig.caveRegionalReductionPercentage = 0;
        WGConfig.caveCircularRoomReductionPercentage = 0;
        WGConfig.caveRavineCaveReductionPercentage = 0;
        WGConfig.caveVerticalReductionPercentage = 0;
        WGConfig.caveMazeReductionPercentage = 0;
        WGConfig.undergWaterLakesChance = 24;
        WGConfig.undergLavaLakesChance = 24;
        WGConfig.waterCaves = true;
        WGConfig.netherCaves = false;
        WGConfig.jumpscare = true;
        WGConfig.serveronly = false;
        WGConfig.liliesChance = 0.5f;
        WGConfig.treeChance = 0.5f;
        WGConfig.glowLilies = 1;
        WGConfig.generationDensity = 0.8f;
        WGConfig.secondYLevel = true;
        WGConfig.enableEntities = true;
        WGConfig.glowSlimesSpawnWater = true;
        WGConfig.floodLevel = 4;
        WGConfig.floodMech = 1;
        WGConfig.cavernsSpawnMultiplier = 1;
        WGConfig.cavesSpawnMultiplier = 1;
        WGConfig.oldBigCavesSpawnMultiplier = 1;
        WGConfig.giantCaveChance = 0;
        WGConfig.entitySmBrSpID = -1;
        WGConfig.entityBrSpID = -1;
        WGConfig.entityLBrSpID = -1;
        WGConfig.entityGlSlID = -1;
        WGConfig.mobSpawnChance = 30;
        WGConfig.CATEGORY_LIMITS = "Hard Limits";
        WGConfig.CATEGORY_WORLD = "World Generation";
        WGConfig.CATEGORY_TYPES = "Cave Types";
        WGConfig.CATEGORY_DECO = "Cave Decoration Chances";
        WGConfig.CATEGORY_MOBS = "Entities";
        WGConfig.CATEGORY_REDUX = "Reduction";
        WGConfig.CATEGORY_MODIF = "Cave Generation Modifiers";
    }
}
